### PR TITLE
Fix Dependency Tree Task Command

### PR DESCRIPTION
**Pull request by ElfoLiNk**
- [x] Ready for review
- [x] Follows CONTRIBUTING rules
- [x] Reviewed by Snyk internal team

#### What does this PR do?

Fix issue #7

### CODE REVIEW

**Comment by darscan** [comment]
Thanks for raising this PR! (and sorry for the delay in getting back to you). I'm trying to manually verify this, but can't seem to reproduce the issue (as I commented here: https://github.com/snyk/snyk-sbt-plugin/issues/7#issuecomment-359760060 ). Could you provide more details on what this PR fixes.. or the configuration I need to make the current implementation fail? Thanks so much

**Comment by ElfoLiNk** [comment]
Hello @darscan i was using sbt 1.x and sbt-dependency-graph 0.9.0

**Comment by darscan** [comment]
Thanks, I'll try that

**Comment by darscan** [comment]
Closing and re-opening for CLA assistant

**Comment by darscan** [comment]
Hello @ElfoLiNk 
I was able to reproduce the issue, and verify that the change is backwards compatible. If you are OK with it, please sign the CLA so I can merge this in. Thanks again

**Comment by ElfoLiNk** [comment]
@darscan CLA signed 👍

**Comment by adrukh** [comment]
@ElfoLiNk thanks for this contribution!

It is now released together with https://github.com/snyk/snyk/releases/tag/v1.69.3

**Pull request merged**
